#!/bin/bash
#	test_select : 사용자 입력에 따라 pwd, date 명령실행

PS3="Input Command (1-3) : "

select cmd in pwd date quit #pwd=1, date=2, quit=3
do
	case $cmd in
	pwd)
		pwd ;;
	date)
		date;;
	quit)
		break;;
	*)
		echo "invaild input, select number";;
	esac
	REPLY=
done
